// Packs scripts/generated_puzzles.json into src/data/puzzles.data.js as a
// base64-obfuscated string. This keeps answers out of casual view-source
// reading (a determined person can still decode them — that's fine, Wordle
// shipped its whole answer list the same way).
//
// Run after regenerating puzzles:  node scripts/pack_puzzles.mjs

import fs from 'node:fs';

const src = new URL('./generated_puzzles.json', import.meta.url);
const out = new URL('../src/data/puzzles.data.js', import.meta.url);

const puzzles = JSON.parse(fs.readFileSync(src, 'utf8'));

// Minimal sanity gate so a bad generator run can never ship.
for (const d of puzzles) {
  if (d.words.length !== 5) throw new Error(`day ${d.day}: needs 5 words`);
  if (d.pool.length !== 8) throw new Error(`day ${d.day}: needs exactly 8 tiles`);
  if (d.words.filter((w) => w.key).length !== 1) throw new Error(`day ${d.day}: needs exactly one keystone`);
  for (const w of d.words) {
    if (w.a + w.b !== w.w) throw new Error(`day ${d.day}: ${w.a}+${w.b} !== ${w.w}`);
  }
}

const b64 = Buffer.from(JSON.stringify(puzzles), 'utf8').toString('base64');

fs.mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true });
fs.writeFileSync(
  out,
  `// Generated by scripts/pack_puzzles.mjs — do not edit by hand.\n// ${puzzles.length} daily puzzles, base64-obfuscated (see script for why).\nexport const PUZZLES_B64 =\n  '${b64}';\n`,
);

console.log(`Packed ${puzzles.length} puzzles into src/data/puzzles.data.js (${Math.round(b64.length / 1024)} KB).`);
