// Packs scripts/generated_puzzles.json into src/data/puzzles.data.js as a
// base64-obfuscated string. This keeps answers out of casual view-source
// reading (a determined person can still decode them — that's fine, Wordle
// shipped its whole answer list the same way).
//
// Run after regenerating puzzles:  node scripts/pack_puzzles.mjs

import fs from 'node:fs';

const src = new URL('./generated_puzzles.json', import.meta.url);
const out = new URL('../src/data/puzzles.data.js', import.meta.url);

const puzzles = JSON.parse(fs.readFileSync(src, 'utf8'));

// Real-word lookup for the fairness rule: melding a real word that isn't one
// of the day's answers must never be called "not a word" (and costs nothing).
// We precompute those per day here so the app doesn't ship a dictionary.
const dict = new Set();
for (const p of ['/usr/share/dict/words', new URL('./common_words_10k.txt', import.meta.url)]) {
  if (!fs.existsSync(p)) continue;
  for (const w of fs.readFileSync(p, 'utf8').split('\n')) {
    const word = w.trim();
    if (/^[a-z]{5,}$/.test(word)) dict.add(word);
  }
}
if (dict.size < 10000) throw new Error('dictionary sources missing — refusing to pack without the real-word list');

for (const d of puzzles) {
  const intendedPairs = new Set(d.words.map((w) => w.a + '+' + w.b));
  const intendedWords = new Set(d.words.map((w) => w.w));
  const ok = new Set();
  for (const a of d.pool) {
    for (const b of d.pool) {
      if (a === b) continue;
      const joined = a + b;
      if (intendedPairs.has(a + '+' + b) || intendedWords.has(joined)) continue;
      if (dict.has(joined.toLowerCase())) ok.add(joined);
    }
  }
  d.ok = [...ok].sort();
}

// Minimal sanity gate so a bad generator run can never ship.
for (const d of puzzles) {
  if (d.words.length !== 5) throw new Error(`day ${d.day}: needs 5 words`);
  if (d.pool.length !== 8) throw new Error(`day ${d.day}: needs exactly 8 tiles`);
  if (d.words.filter((w) => w.key).length !== 1) throw new Error(`day ${d.day}: needs exactly one keystone`);
  for (const w of d.words) {
    if (w.a + w.b !== w.w) throw new Error(`day ${d.day}: ${w.a}+${w.b} !== ${w.w}`);
  }
}

const b64 = Buffer.from(JSON.stringify(puzzles), 'utf8').toString('base64');

fs.mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true });
fs.writeFileSync(
  out,
  `// Generated by scripts/pack_puzzles.mjs — do not edit by hand.\n// ${puzzles.length} daily puzzles, base64-obfuscated (see script for why).\nexport const PUZZLES_B64 =\n  '${b64}';\n`,
);

console.log(`Packed ${puzzles.length} puzzles into src/data/puzzles.data.js (${Math.round(b64.length / 1024)} KB).`);
