// Hand-curated candidate words, grouped by theme for tonal consistency with
// the original 14 puzzles (cozy / nature / home / gentle-adventure vibe).
//
// These are meant to be genuine, ordinary single dictionary words (the same
// way the original puzzles used GARDEN, WINTER, CASTLE, KETTLE — real single
// words, not two words jammed together). Every word here still gets
// cross-checked against a real dictionary by generate_puzzles.mjs before
// it's allowed into a puzzle — nothing here is trusted blindly.

export const WORD_BANK = {
  trees: ['acorn', 'maple', 'willow', 'birch', 'cedar', 'spruce', 'sapling', 'branch', 'blossom', 'orchard', 'grove', 'timber', 'lumber', 'sawdust', 'firewood', 'kindling', 'bramble', 'thicket', 'hedgerow', 'canopy', 'foliage', 'evergreen', 'pinecone', 'chestnut', 'walnut', 'hazelnut', 'mistletoe', 'holly', 'ivy', 'moss', 'fern', 'lichen'],
  flowers: ['tulip', 'daisy', 'poppy', 'violet', 'jasmine', 'lilac', 'magnolia', 'marigold', 'dandelion', 'sunflower', 'buttercup', 'foxglove', 'honeysuckle', 'lavender', 'clover', 'thistle', 'nettle', 'orchid', 'crocus', 'daffodil', 'bouquet', 'blossom', 'petal', 'meadow', 'wildflower', 'garland', 'wreath', 'bramble'],
  herbs: ['rosemary', 'basil', 'cilantro', 'oregano', 'parsley', 'fennel', 'saffron', 'nutmeg', 'cinnamon', 'ginger', 'vanilla', 'clove', 'paprika', 'turmeric', 'mustard', 'sesame', 'chamomile'],
  woodland: ['badger', 'otter', 'beaver', 'weasel', 'ferret', 'hedgehog', 'squirrel', 'chipmunk', 'raccoon', 'opossum', 'skunk', 'coyote', 'bobcat', 'antler', 'burrow', 'hollow', 'thicket', 'clearing', 'underbrush', 'toadstool', 'mushroom'],
  birds: ['sparrow', 'robin', 'cardinal', 'bluejay', 'chickadee', 'nuthatch', 'woodpecker', 'hummingbird', 'swallow', 'falcon', 'osprey', 'kestrel', 'buzzard', 'vulture', 'ostrich', 'peacock', 'pheasant', 'partridge', 'flamingo', 'pelican', 'heron', 'stork', 'crane', 'puffin', 'penguin', 'seagull', 'sparrow', 'feather', 'plumage', 'nesting', 'fledgling', 'eggshell'],
  savanna: ['elephant', 'giraffe', 'zebra', 'antelope', 'buffalo', 'gazelle', 'cheetah', 'leopard', 'panther', 'jaguar', 'cougar', 'wildebeest', 'hyena', 'warthog', 'rhino', 'hippo', 'meerkat', 'baboon', 'ostrich'],
  arctic: ['walrus', 'narwhal', 'iceberg', 'glacier', 'penguin', 'polar', 'blizzard', 'avalanche', 'snowdrift', 'icicle', 'tundra', 'aurora', 'permafrost', 'crevasse', 'igloo', 'husky', 'sled'],
  smallmammals: ['kangaroo', 'koala', 'wombat', 'platypus', 'echidna', 'armadillo', 'anteater', 'sloth', 'chinchilla', 'hamster', 'gerbil', 'lemur', 'mongoose', 'porcupine'],
  babyanimals: ['kitten', 'puppy', 'gosling', 'duckling', 'piglet', 'lamb', 'foal', 'calf', 'cygnet', 'tadpole', 'caterpillar', 'cocoon', 'chrysalis', 'fledgling'],
  bakery: ['pretzel', 'biscuit', 'muffin', 'waffle', 'crumpet', 'scone', 'croissant', 'baguette', 'dumpling', 'brownie', 'shortbread', 'gingerbread', 'macaron', 'biscotti', 'flapjack', 'oatcake', 'custard', 'pudding', 'meringue', 'marzipan', 'praline', 'toffee', 'caramel', 'fudge', 'nougat', 'licorice', 'lollipop', 'gumdrop', 'marmalade', 'preserves', 'molasses'],
  savorykitchen: ['noodle', 'dumpling', 'chowder', 'gumbo', 'risotto', 'casserole', 'skillet', 'griddle', 'kettle', 'cauldron', 'ladle', 'spatula', 'colander', 'saucepan', 'teakettle', 'teacup', 'saucer', 'goblet', 'chalice', 'platter', 'napkin', 'apron', 'pantry', 'cupboard', 'cellar', 'harvest'],
  breakfast: ['pancake', 'oatmeal', 'granola', 'yogurt', 'omelet', 'sausage', 'porridge', 'cereal', 'syrup', 'butter', 'toaster', 'brunch', 'creamer'],
  dairy: ['cheddar', 'parmesan', 'ricotta', 'yogurt', 'buttermilk', 'creamery', 'farmstead', 'milkmaid', 'churn'],
  home: ['blanket', 'cushion', 'curtain', 'drapery', 'mattress', 'hammock', 'cradle', 'wardrobe', 'dresser', 'cabinet', 'cupboard', 'rafter', 'chimney', 'mantle', 'chandelier', 'lantern', 'sconce', 'doorway', 'doorstep', 'windowsill', 'shutter', 'awning', 'veranda', 'balcony', 'terrace', 'courtyard', 'driveway', 'pathway', 'stairway', 'banister', 'doorknob', 'keyhole', 'padlock', 'hinge', 'trellis', 'gazebo', 'birdbath', 'flowerpot', 'wallpaper', 'floorboard', 'staircase', 'threshold', 'doormat'],
  attic: ['cobweb', 'trunk', 'rafters', 'skylight', 'keepsake', 'heirloom', 'candlestick', 'lampshade', 'quilt', 'mirror', 'hatch', 'ladder'],
  weather: ['thunder', 'lightning', 'sunshine', 'twilight', 'daybreak', 'nightfall', 'moonlight', 'starlight', 'snowfall', 'snowflake', 'blizzard', 'hurricane', 'tornado', 'monsoon', 'drizzle', 'downpour', 'overcast', 'forecast', 'humidity', 'breeze', 'gale', 'gust', 'whirlwind', 'tempest', 'frost', 'puddle', 'rainfall', 'cloudburst', 'sunrise', 'sunset', 'rainbow'],
  time: ['morning', 'evening', 'midnight', 'noontime', 'daytime', 'weekday', 'weekend', 'holiday', 'birthday', 'calendar', 'almanac', 'harvest', 'autumn', 'springtime'],
  ocean: ['seashell', 'starfish', 'seahorse', 'sandcastle', 'lighthouse', 'boardwalk', 'seagull', 'driftwood', 'shoreline', 'saltwater', 'harbor', 'anchor', 'seaweed', 'coastline', 'pier', 'fisherman', 'sailboat', 'compass', 'lagoon', 'tidepool', 'shipwreck', 'treasure', 'castaway', 'coconut', 'palmtree', 'cove', 'reef', 'sandbar', 'jellyfish', 'octopus', 'stingray', 'plankton', 'submarine', 'clamshell', 'urchin', 'barnacle', 'current'],
  mountains: ['summit', 'boulder', 'canyon', 'cliffside', 'trailhead', 'basecamp', 'glacier', 'avalanche', 'foothill', 'plateau', 'alpine', 'ledge', 'cavern', 'ravine', 'valley'],
  desert: ['cactus', 'oasis', 'mirage', 'mesa', 'tumbleweed', 'scorpion', 'lizard', 'camel', 'sandstorm', 'vulture', 'sagebrush', 'horizon'],
  farm: ['barnyard', 'haystack', 'tractor', 'pasture', 'stable', 'henhouse', 'rooster', 'donkey', 'silo', 'trough', 'pitchfork', 'granary', 'shepherd', 'scarecrow', 'cornfield', 'wheatfield', 'vineyard', 'windmill', 'millstone', 'countryside'],
  garden: ['flowerbed', 'wheelbarrow', 'greenhouse', 'topiary', 'compost', 'seedling', 'rosebush', 'hydrangea', 'archway', 'watering'],
  pond: ['dragonfly', 'minnow', 'cattail', 'ripple', 'brook', 'stream', 'pebble', 'reflection'],
  celestial: ['starlight', 'moonbeam', 'constellation', 'telescope', 'comet', 'meteor', 'stardust', 'galaxy', 'crescent', 'eclipse', 'astronomer', 'rocket', 'astronaut', 'satellite', 'asteroid', 'nebula', 'countdown', 'planetoid'],
  fantasy: ['dragon', 'unicorn', 'goblin', 'wizard', 'sorcerer', 'knight', 'kingdom', 'palace', 'legend', 'folklore', 'mermaid', 'giant', 'gnome', 'sprite', 'enchanted', 'castle', 'drawbridge', 'shield', 'armor', 'lance', 'banner', 'chainlink', 'gauntlet', 'helmet', 'squire', 'stronghold', 'courtyard', 'throne', 'potion', 'cauldron', 'amulet', 'talisman', 'alchemist', 'elixir', 'crystal'],
  pirate: ['treasure', 'compass', 'parchment', 'anchor', 'plunder', 'galleon', 'cutlass', 'seafarer', 'buried'],
  jungle: ['rainforest', 'canopy', 'monkey', 'parrot', 'toucan', 'jaguar', 'waterfall', 'orchid', 'bamboo', 'macaw', 'python', 'tropical', 'humidity', 'undergrowth', 'clearing', 'explorer', 'expedition'],
  circus: ['carnival', 'parade', 'confetti', 'streamer', 'bunting', 'firework', 'balloon', 'carousel', 'juggler', 'acrobat', 'trumpet', 'fanfare', 'costume'],
  celebration: ['birthday', 'confetti', 'garland', 'present', 'ribbon', 'cupcake', 'balloon', 'invitation', 'anniversary', 'keepsake', 'sparkler', 'banner', 'festivity'],
  insects: ['ladybug', 'firefly', 'cricket', 'beetle', 'dragonfly', 'butterfly', 'caterpillar', 'grasshopper', 'honeycomb', 'beekeeper', 'nectar', 'pollinate', 'antenna', 'wingspan'],
  toys: ['marble', 'pinwheel', 'puppet', 'jigsaw', 'kite', 'balloon', 'whistle', 'wagon', 'seesaw', 'carousel', 'trampoline', 'dollhouse'],
  school: ['classroom', 'notebook', 'chalkboard', 'pencil', 'crayon', 'backpack', 'playground', 'recess', 'homework', 'alphabet', 'lunchbox', 'scissors', 'eraser', 'textbook', 'teacher', 'student'],
  library: ['bookshelf', 'bookmark', 'chapter', 'parchment', 'scholar', 'archive', 'catalog', 'binding', 'footnote', 'preface', 'anthology', 'librarian', 'hardcover', 'paperback', 'notebook', 'textbook'],
  crafts: ['knitting', 'crochet', 'embroidery', 'thimble', 'stitching', 'quilting', 'pottery', 'ceramic', 'woodworking', 'whittling', 'origami', 'scrapbook', 'beading', 'weaving', 'tapestry', 'calligraphy'],
  workshop: ['blacksmith', 'anvil', 'hammer', 'sawdust', 'workbench', 'carpenter', 'chisel', 'lumber', 'sandpaper', 'blueprint', 'clockwork', 'pulley', 'bellows', 'forge', 'wrench', 'varnish'],
  invention: ['gadget', 'contraption', 'clockwork', 'tinkerer', 'workshop', 'prototype', 'mechanism', 'apparatus', 'flywheel', 'lever', 'pulley', 'cogwheel', 'sprocket', 'dynamo', 'gizmo'],
  laboratory: ['beaker', 'potion', 'cauldron', 'formula', 'chemistry', 'alchemist', 'elixir', 'mixture', 'goggles', 'microscope', 'specimen', 'experiment', 'flask', 'crucible', 'compound'],
  music: ['trumpet', 'guitar', 'tempo', 'drummer', 'melody', 'harmony', 'rhythm', 'concert', 'orchestra', 'symphony', 'ballad', 'chorus', 'lullaby', 'serenade', 'fiddle', 'clarinet', 'cymbal', 'ukulele', 'harmonica', 'tambourine'],
  market: ['peddler', 'merchant', 'cobblestone', 'storefront', 'signpost', 'vendor', 'satchel', 'ledger', 'burlap', 'crate', 'barrel', 'wagon', 'awning'],
  wardrobe: ['sweater', 'scarf', 'mitten', 'bonnet', 'slipper', 'nightgown', 'pajama', 'overcoat', 'raincoat', 'umbrella', 'galoshes', 'buckle', 'button', 'ribbon', 'stitching'],
  colors: ['crimson', 'scarlet', 'emerald', 'sapphire', 'amber', 'copper', 'bronze', 'silver', 'golden', 'ivory', 'coral', 'lavender', 'mauve', 'indigo', 'violet', 'turquoise'],
  gems: ['diamond', 'emerald', 'sapphire', 'ruby', 'garnet', 'opal', 'topaz', 'amethyst', 'pearl', 'crystal', 'jewel', 'locket', 'brooch', 'necklace', 'bracelet'],
  seasonsfeel: ['harvest', 'pumpkin', 'cider', 'hayride', 'foliage', 'acorn', 'blossom', 'sprout', 'seedling', 'picnic', 'lemonade', 'sunburn', 'sandcastle', 'popsicle', 'snowball', 'snowman', 'mitten', 'earmuff', 'sledding', 'toboggan'],

  fruits: ['apple', 'banana', 'orange', 'lemon', 'cherry', 'peach', 'plum', 'apricot', 'mango', 'papaya', 'pomegranate', 'pineapple', 'strawberry', 'blueberry', 'raspberry', 'blackberry', 'cranberry', 'grapefruit', 'tangerine', 'nectarine', 'watermelon', 'cantaloupe', 'kiwi', 'guava', 'lychee', 'persimmon', 'fig', 'date', 'currant', 'gooseberry'],
  vegetables: ['carrot', 'potato', 'tomato', 'cucumber', 'pumpkin', 'squash', 'zucchini', 'eggplant', 'cabbage', 'lettuce', 'spinach', 'broccoli', 'cauliflower', 'radish', 'turnip', 'parsnip', 'beetroot', 'celery', 'artichoke', 'asparagus', 'onion', 'garlic', 'pepper', 'mushroom', 'pea'],
  vehicles: ['bicycle', 'tricycle', 'scooter', 'wagon', 'carriage', 'chariot', 'caboose', 'locomotive', 'streetcar', 'sailboat', 'canoe', 'kayak', 'rowboat', 'schooner', 'submarine', 'airplane', 'biplane', 'helicopter', 'balloon', 'wheelbarrow', 'sled', 'sleigh', 'skateboard', 'gondola'],
  buildings: ['cottage', 'cabin', 'mansion', 'bungalow', 'farmhouse', 'lighthouse', 'windmill', 'watermill', 'barn', 'stable', 'greenhouse', 'treehouse', 'castle', 'palace', 'chapel', 'monastery', 'observatory', 'planetarium', 'bakery', 'bookstore', 'schoolhouse', 'firehouse', 'lodge', 'cottage', 'chalet'],
  clothing2: ['sweater', 'cardigan', 'poncho', 'shawl', 'muffler', 'earmuff', 'mitten', 'glove', 'legwarmer', 'jacket', 'raincoat', 'overcoat', 'trenchcoat', 'jumpsuit', 'overalls', 'apron', 'bandana', 'headband', 'necktie', 'bowtie', 'suspenders', 'moccasin', 'sandal', 'sneaker', 'loafer'],
  sports: ['baseball', 'football', 'basketball', 'volleyball', 'badminton', 'ping', 'archery', 'fencing', 'wrestling', 'gymnastics', 'swimming', 'diving', 'rowing', 'cycling', 'marathon', 'relay', 'hurdle', 'javelin', 'discus', 'skateboard'],
  containers: ['basket', 'crate', 'barrel', 'bucket', 'pouch', 'satchel', 'knapsack', 'suitcase', 'trunk', 'chest', 'jar', 'canister', 'flask', 'thermos', 'pitcher', 'urn', 'vase', 'bin', 'hamper', 'crib'],
  beverages: ['lemonade', 'cider', 'cocoa', 'coffee', 'espresso', 'cappuccino', 'smoothie', 'milkshake', 'seltzer', 'ginger', 'chamomile', 'peppermint', 'eggnog', 'punch', 'nectar'],
  reptiles: ['lizard', 'gecko', 'iguana', 'chameleon', 'salamander', 'newt', 'turtle', 'tortoise', 'crocodile', 'alligator', 'python', 'cobra', 'viper', 'anaconda', 'komodo'],
  seacreatures2: ['dolphin', 'porpoise', 'narwhal', 'walrus', 'manatee', 'seal', 'otter', 'penguin', 'pelican', 'albatross', 'seagull', 'crab', 'lobster', 'shrimp', 'oyster', 'mussel', 'clam', 'squid', 'shark', 'whale', 'guppy', 'goldfish', 'minnow', 'salmon', 'trout'],
  geography: ['valley', 'canyon', 'plateau', 'peninsula', 'archipelago', 'isthmus', 'lagoon', 'estuary', 'delta', 'glacier', 'volcano', 'crater', 'cavern', 'grotto', 'gorge', 'ravine', 'meadow', 'prairie', 'savanna', 'tundra', 'marshland', 'wetland', 'floodplain', 'foothill', 'highland'],
  tools: ['hammer', 'wrench', 'screwdriver', 'pliers', 'chisel', 'mallet', 'crowbar', 'handsaw', 'level', 'clamp', 'toolbox', 'ladder', 'shovel', 'rake', 'trowel', 'pitchfork', 'wheelbarrow', 'lantern', 'flashlight', 'measuring'],
  textiles: ['cotton', 'linen', 'flannel', 'velvet', 'satin', 'silk', 'wool', 'burlap', 'canvas', 'tweed', 'corduroy', 'gingham', 'calico', 'muslin', 'fleece', 'yarn', 'thread', 'needle', 'thimble', 'button'],
  professions: ['carpenter', 'blacksmith', 'baker', 'butcher', 'farmer', 'shepherd', 'fisherman', 'sailor', 'librarian', 'teacher', 'gardener', 'painter', 'potter', 'weaver', 'tailor', 'cobbler', 'jeweler', 'merchant', 'peddler', 'innkeeper', 'lighthousekeeper', 'beekeeper', 'astronomer', 'alchemist', 'wizard'],
  campgear: ['tent', 'lantern', 'canteen', 'compass', 'backpack', 'sleepingbag', 'flashlight', 'binoculars', 'firewood', 'kindling', 'campfire', 'marshmallow', 'trailmix', 'hammock', 'hatchet', 'rope', 'whistle', 'mapcase'],
  wintersports: ['skiing', 'skating', 'sledding', 'snowboard', 'toboggan', 'iceskate', 'snowshoe', 'curling', 'hockey', 'bobsled'],
  desserts2: ['sundae', 'parfait', 'trifle', 'tiramisu', 'cheesecake', 'shortcake', 'strudel', 'cobbler', 'crumble', 'tart', 'eclair', 'profiterole', 'baklava', 'sorbet', 'gelato', 'custard', 'flan'],
  condiments: ['ketchup', 'mustard', 'mayonnaise', 'vinegar', 'relish', 'chutney', 'marinade', 'dressing', 'gravy', 'sauce', 'salsa', 'hummus', 'pesto'],
  breadtypes: ['baguette', 'ciabatta', 'focaccia', 'brioche', 'pretzel', 'bagel', 'biscuit', 'cornbread', 'sourdough', 'flatbread', 'breadstick', 'tortilla', 'muffin', 'scone', 'crumpet'],
  teahouse: ['teapot', 'teacup', 'saucer', 'kettle', 'chamomile', 'peppermint', 'jasmine', 'oolong', 'matcha', 'chai', 'honey', 'biscuit', 'shortbread'],
  bathhome: ['bathtub', 'washbasin', 'towel', 'bathrobe', 'slipper', 'soapdish', 'sponge', 'mirror', 'candle', 'lavender', 'chamomile'],
  bedroom: ['blanket', 'pillow', 'mattress', 'nightstand', 'lampshade', 'curtain', 'closet', 'dresser', 'quilt', 'bedspread', 'nightlight', 'alarm'],
  laundry: ['basket', 'clothesline', 'clothespin', 'detergent', 'fabric', 'softener', 'ironing', 'wrinkle', 'ribbon', 'button'],
  playground2: ['seesaw', 'swingset', 'sandbox', 'slide', 'jungle', 'monkeybar', 'merrygoround', 'hopscotch', 'marbles', 'jumprope', 'kickball', 'frisbee'],
  autumnholiday: ['pumpkin', 'harvest', 'scarecrow', 'cornstalk', 'hayride', 'cider', 'acorn', 'chestnut', 'foliage', 'costume', 'lantern', 'cauldron', 'candy', 'basket'],
  springholiday: ['blossom', 'tulip', 'daffodil', 'bunny', 'basket', 'bonnet', 'ribbon', 'garland', 'meadow', 'sprout', 'shower', 'umbrella'],
  summerholiday: ['picnic', 'firework', 'lemonade', 'sparkler', 'parade', 'barbecue', 'banner', 'garland', 'watermelon', 'popsicle', 'bunting'],
  winterholiday: ['garland', 'ornament', 'tinsel', 'stocking', 'mistletoe', 'gingerbread', 'eggnog', 'sleigh', 'reindeer', 'snowglobe', 'candycane', 'wreath', 'lantern', 'carol'],
  riverlife: ['kayak', 'canoe', 'paddle', 'rapids', 'waterfall', 'driftwood', 'pebble', 'streambed', 'riverbank', 'ferry', 'raft', 'current'],
  cavelife: ['stalactite', 'stalagmite', 'cavern', 'grotto', 'crystal', 'tunnel', 'echo', 'lantern', 'boulder', 'passageway'],
  volcano: ['volcano', 'crater', 'magma', 'lava', 'eruption', 'ash', 'obsidian', 'geyser', 'sulfur', 'basalt'],
  astronomy2: ['telescope', 'observatory', 'planetarium', 'constellation', 'galaxy', 'nebula', 'meteorite', 'comet', 'asteroid', 'satellite', 'astronaut', 'cosmonaut', 'spaceship', 'moonwalk', 'stardust', 'orbiter'],
  theater: ['costume', 'curtain', 'spotlight', 'playbill', 'orchestra', 'balcony', 'rehearsal', 'backstage', 'marquee', 'audience', 'encore', 'matinee'],
  dance: ['ballet', 'waltz', 'tango', 'ballroom', 'twirl', 'pirouette', 'slipper', 'costume', 'rhythm', 'melody'],
  cookingverbs: ['baking', 'roasting', 'simmering', 'boiling', 'toasting', 'grilling', 'whisking', 'kneading', 'frosting', 'seasoning', 'marinating', 'stewing', 'poaching', 'blending'],
  farmtools: ['pitchfork', 'plow', 'harrow', 'scythe', 'sickle', 'tractor', 'trough', 'silo', 'granary', 'wheelbarrow', 'rake', 'hoe', 'shovel'],
  sewingcraft: ['needle', 'thimble', 'thread', 'button', 'buckle', 'ribbon', 'zipper', 'pattern', 'fabric', 'seamstress', 'embroidery', 'tapestry', 'quilt', 'patchwork'],
  papercraft: ['origami', 'scrapbook', 'notebook', 'envelope', 'parchment', 'calligraphy', 'bookmark', 'stationery', 'postcard', 'wrapping', 'ribbon', 'stamp'],
  footwear: ['sandal', 'sneaker', 'loafer', 'moccasin', 'slipper', 'boot', 'sock', 'legwarmer', 'galoshes', 'clog'],
  headwear: ['bonnet', 'beanie', 'headband', 'earmuff', 'helmet', 'crown', 'tiara', 'wreath', 'garland', 'veil'],
  hardware: ['hinge', 'latch', 'padlock', 'buckle', 'bracket', 'bolt', 'screw', 'washer', 'nail', 'clamp'],
  woodcraft: ['whittling', 'carving', 'sanding', 'varnish', 'lumber', 'sawdust', 'plank', 'timber', 'chisel', 'workbench'],
  fishinglife: ['fishing', 'tackle', 'reel', 'bait', 'hook', 'net', 'boat', 'dock', 'pier', 'wader', 'creel', 'lure', 'angler'],
  boatinglife: ['sailboat', 'schooner', 'anchor', 'harbor', 'compass', 'mast', 'rudder', 'deckhand', 'lighthouse', 'lifejacket', 'oar', 'paddle'],
  aviation: ['airplane', 'biplane', 'glider', 'hangar', 'runway', 'cockpit', 'propeller', 'parachute', 'aviator', 'airfield'],
  trainlife: ['locomotive', 'caboose', 'railway', 'boxcar', 'conductor', 'platform', 'depot', 'whistle', 'trestle', 'tunnel'],
  bugsgarden: ['ladybug', 'firefly', 'cricket', 'grasshopper', 'butterfly', 'caterpillar', 'dragonfly', 'honeybee', 'bumblebee', 'beetle', 'spider', 'cobweb', 'anthill'],
  spicerack: ['cinnamon', 'nutmeg', 'clove', 'ginger', 'vanilla', 'cardamom', 'saffron', 'turmeric', 'paprika', 'oregano', 'rosemary', 'thyme', 'basil', 'fennel', 'chamomile'],

  rocksminerals: ['granite', 'limestone', 'sandstone', 'obsidian', 'quartz', 'crystal', 'marble', 'slate', 'boulder', 'pebble', 'gravel', 'mineral', 'fossil', 'amber', 'flint'],
  waterways: ['waterfall', 'rapids', 'lagoon', 'river', 'brook', 'creek', 'stream', 'spring', 'marsh', 'swamp', 'wetland', 'lake', 'pond', 'delta', 'estuary', 'fjord', 'channel', 'harbor'],
  reading: ['journal', 'diary', 'memoir', 'biography', 'pamphlet', 'brochure', 'almanac', 'anthology', 'chapter', 'preface', 'footnote', 'glossary', 'appendix', 'foreword', 'epilogue'],
  academics: ['alphabet', 'arithmetic', 'grammar', 'spelling', 'vocabulary', 'dictionary', 'encyclopedia', 'geometry', 'chemistry', 'geography', 'astronomy', 'biology', 'history'],
  skywords: ['sunbeam', 'moonrise', 'moonset', 'stardust', 'skyline', 'horizon', 'daybreak', 'twilight', 'dusk', 'dawn', 'zenith', 'meteor', 'comet', 'aurora'],
  cookingtools: ['whisk', 'grater', 'spatula', 'ladle', 'colander', 'skillet', 'griddle', 'saucepan', 'cauldron', 'mortar', 'pestle', 'strainer', 'tongs', 'peeler', 'rollingpin'],
  countryside: ['farmland', 'cropland', 'meadow', 'pasture', 'hedgerow', 'orchard', 'vineyard', 'cottage', 'farmhouse', 'barnyard', 'windmill', 'haystack', 'scarecrow'],
  moregarden: ['trellis', 'gazebo', 'topiary', 'birdbath', 'sundial', 'archway', 'pathway', 'flowerbed', 'greenhouse', 'wheelbarrow', 'compost', 'watering'],
  moreinsects: ['mayfly', 'mantis', 'cicada', 'termite', 'earwig', 'aphid', 'weevil', 'hornet', 'wasp', 'firefly', 'ladybug', 'cricket'],
  amphibians: ['frog', 'toad', 'newt', 'salamander', 'tadpole', 'polliwog'],
  keepsakes: ['memento', 'souvenir', 'artifact', 'relic', 'heirloom', 'keepsake', 'trinket', 'treasure', 'antique', 'trophy', 'medallion'],
  magicwords: ['enchantment', 'incantation', 'spellbook', 'grimoire', 'moonstone', 'sorcery', 'wizardry', 'alchemy', 'potion', 'talisman', 'amulet', 'charm'],
  fireside: ['fireplace', 'firewood', 'kindling', 'bonfire', 'campfire', 'ember', 'charcoal', 'chimney', 'hearth', 'lantern', 'candlelight', 'flicker'],
  pathways: ['footpath', 'trailhead', 'stepping', 'boardwalk', 'cobblestone', 'crossroads', 'byway', 'lane', 'trail', 'avenue', 'promenade'],
  moreflowers: ['peony', 'zinnia', 'begonia', 'petunia', 'geranium', 'carnation', 'chrysanthemum', 'hyacinth', 'snowdrop', 'primrose', 'buttercup', 'cowslip'],
  weatherphenomena: ['rainbow', 'raindrop', 'snowdrift', 'hailstone', 'thunderclap', 'lightning', 'windstorm', 'downpour', 'drizzle', 'mist', 'haze', 'frost', 'dew', 'humidity'],
  outdoorplay: ['hopscotch', 'jumprope', 'kickball', 'frisbee', 'sandbox', 'seesaw', 'swingset', 'trampoline', 'pinwheel', 'kite', 'bubble', 'chalk'],
  candles: ['candlelight', 'candlestick', 'candlewick', 'beeswax', 'lantern', 'firefly', 'glowworm', 'nightlight'],
  seasonsmore: ['equinox', 'solstice', 'harvest', 'blossom', 'foliage', 'frost', 'thaw', 'bloom', 'sprout', 'wither'],
  gemsmore: ['moonstone', 'birthstone', 'gemstone', 'amethyst', 'turquoise', 'aquamarine', 'citrine', 'peridot', 'onyx', 'jade'],
  storytelling: ['storyteller', 'narrator', 'legend', 'fable', 'parable', 'ballad', 'saga', 'chronicle', 'folktale', 'proverb', 'riddle', 'mystery'],
  gameroom: ['checkers', 'dominoes', 'crossword', 'puzzle', 'riddle', 'boardgame', 'playingcard', 'marbles', 'yoyo', 'kaleidoscope'],
  morebuildings: ['cornerstone', 'foundation', 'rooftop', 'chimney', 'balcony', 'archway', 'doorway', 'stairway', 'hallway', 'entryway', 'threshold'],
  campfirefood: ['marshmallow', 'skewer', 'kabob', 'popcorn', 'roastedcorn', 'hotdog', 'campfire', 'ember', 'grill', 'charcoal'],
  toolshed: ['wheelbarrow', 'pitchfork', 'rake', 'shovel', 'trowel', 'hoe', 'shears', 'clippers', 'ladder', 'toolbox', 'workbench'],
  moremusic: ['accordion', 'bagpipe', 'xylophone', 'triangle', 'castanet', 'maracas', 'bugle', 'trombone', 'saxophone', 'clarinet', 'mandolin', 'banjo'],
  celebrations2: ['festivity', 'jubilee', 'gathering', 'reunion', 'ceremony', 'procession', 'pageant', 'fanfare', 'toast', 'tribute'],
  nightwords: ['nightfall', 'nightlight', 'nighttime', 'nightgown', 'nightcap', 'moonlit', 'starlit', 'lullaby', 'bedtime', 'dreamland', 'slumber', 'snooze'],

  shapes: ['circle', 'square', 'triangle', 'rectangle', 'oval', 'hexagon', 'pentagon', 'octagon', 'diamond', 'crescent', 'spiral', 'sphere', 'cylinder', 'pyramid'],
  morecolors: ['maroon', 'burgundy', 'periwinkle', 'cerulean', 'vermilion', 'chartreuse', 'magenta', 'fuchsia', 'ochre', 'sienna', 'charcoal', 'ivory', 'ebony', 'alabaster'],
  metals: ['gold', 'silver', 'platinum', 'bronze', 'copper', 'brass', 'pewter', 'aluminum', 'titanium', 'nickel', 'cobalt'],
  fantasycreatures: ['griffin', 'phoenix', 'pegasus', 'centaur', 'mermaid', 'kraken', 'basilisk', 'chimera', 'unicorn', 'dragon', 'sphinx', 'yeti', 'gremlin', 'goblin', 'troll', 'ogre', 'fairy', 'pixie', 'nymph', 'siren'],
  adventure: ['voyage', 'odyssey', 'quest', 'pilgrimage', 'expedition', 'exploration', 'wanderer', 'journey', 'trek', 'safari', 'excursion', 'crossing'],
  naturephenomena: ['rainbow', 'aurora', 'mirage', 'echo', 'ripple', 'shadow', 'silhouette', 'reflection', 'shimmer', 'glimmer', 'sparkle', 'twinkle', 'glisten'],
  moretrees: ['sycamore', 'magnolia', 'dogwood', 'redwood', 'sequoia', 'cypress', 'juniper', 'poplar', 'elm', 'oak', 'ash', 'beech', 'alder', 'hickory'],
  moreflowers2: ['gardenia', 'camellia', 'azalea', 'begonia', 'iris', 'lily', 'orchid', 'aster', 'zinnia', 'anemone', 'freesia', 'gladiolus'],
  moreveg: ['rutabaga', 'kohlrabi', 'fennel', 'leek', 'shallot', 'chive', 'watercress', 'endive', 'chicory', 'okra', 'jicama'],
  morefruit: ['boysenberry', 'elderberry', 'mulberry', 'huckleberry', 'quince', 'kumquat', 'starfruit', 'passionfruit', 'dragonfruit', 'jackfruit'],
  weatherinstruments: ['barometer', 'thermometer', 'anemometer', 'windvane', 'weathervane', 'raingauge', 'hygrometer'],
  morebirds: ['warbler', 'thrush', 'wren', 'lark', 'starling', 'magpie', 'kingfisher', 'oriole', 'grosbeak', 'towhee', 'plover', 'sandpiper', 'egret', 'ibis', 'bittern', 'grebe', 'loon', 'swan', 'goose', 'mallard'],
  moresea: ['barracuda', 'anemone', 'seacucumber', 'nautilus', 'seasnail', 'periwinkle', 'limpet', 'cockle', 'scallop', 'abalone'],
  spacecraft: ['spaceship', 'starship', 'shuttle', 'capsule', 'module', 'satellite', 'probe', 'rover', 'lander', 'orbiter', 'spacesuit', 'helmet'],
  musicalgear: ['metronome', 'tuningfork', 'sheetmusic', 'songbook', 'conductor', 'orchestra', 'ensemble', 'quartet', 'quintet', 'chorus'],
  cookingmethods: ['barbecue', 'casserole', 'marinade', 'seasoning', 'garnish', 'appetizer', 'entree', 'dessert', 'beverage', 'delicacy'],
  farmproduce: ['harvest', 'produce', 'orchard', 'vineyard', 'cropland', 'granary', 'silage', 'fodder', 'compost', 'fertilizer', 'irrigation'],
  weathercozy: ['fireside', 'blanket', 'sweater', 'cocoa', 'candlelight', 'raindrop', 'puddle', 'umbrella', 'galoshes', 'thunder'],
  islandlife: ['coconut', 'palmtree', 'hammock', 'lagoon', 'shoreline', 'seabreeze', 'tropical', 'paradise', 'castaway', 'shipwreck'],
  wintercozy: ['snowdrift', 'icicle', 'frostbite', 'earmuff', 'mitten', 'scarf', 'hotcocoa', 'fireplace', 'blanket', 'sweater', 'thermos'],
  gardening2: ['seedling', 'sapling', 'cutting', 'fertilizer', 'irrigation', 'greenhouse', 'terrarium', 'planter', 'flowerpot', 'trellis', 'arbor'],
  bookish: ['bookworm', 'bookshelf', 'bookmark', 'bookplate', 'booklet', 'chapbook', 'yearbook', 'notebook', 'sketchbook', 'guidebook', 'handbook'],
  timepieces: ['clockwork', 'pendulum', 'hourglass', 'sundial', 'stopwatch', 'wristwatch', 'cuckoo', 'chime'],
  cheerful: ['sunshine', 'rainbow', 'giggles', 'sparkle', 'twinkle', 'blossom', 'bumblebee', 'ladybug', 'butterfly', 'daydream'],
  farmanimals2: ['gosling', 'gander', 'drake', 'tomcat', 'billygoat', 'nannygoat', 'stallion', 'foal', 'colt', 'filly', 'heifer'],

  moregeography: ['highland', 'lowland', 'woodland', 'grassland', 'farmland', 'wasteland', 'homeland', 'mainland', 'headland', 'wetland', 'moorland', 'heathland'],
  morearchitecture: ['scaffold', 'buttress', 'colonnade', 'archway', 'rotunda', 'turret', 'parapet', 'portico', 'facade', 'vestibule', 'atrium', 'foyer'],
  hobbies2: ['stargazing', 'birdwatching', 'photography', 'journaling', 'gardening', 'beekeeping', 'fishing', 'hiking', 'camping', 'painting', 'sketching', 'sculpting'],
  moreacademic: ['algebra', 'calculus', 'physics', 'anatomy', 'ecology', 'genetics', 'geology', 'zoology', 'botany', 'mythology', 'archaeology', 'sociology'],
  vessels: ['pitcher', 'goblet', 'chalice', 'tankard', 'decanter', 'carafe', 'canteen', 'flagon', 'urn', 'ewer', 'ladle', 'tureen'],
  moregames: ['charades', 'scavenger', 'tugofwar', 'leapfrog', 'dodgeball', 'kickball', 'tetherball', 'foursquare', 'redlight', 'simonsays'],
  directions: ['northward', 'southward', 'eastward', 'westward', 'upward', 'downward', 'homeward', 'onward', 'forward', 'backward', 'skyward', 'seaward'],
  morefabric: ['chenille', 'chambray', 'organza', 'brocade', 'damask', 'jacquard', 'seersucker', 'chiffon', 'taffeta', 'cashmere'],
  morecooking: ['simmering', 'steaming', 'braising', 'poaching', 'blanching', 'searing', 'toasting', 'caramelizing', 'fermenting', 'pickling'],
  moreinstruments: ['harpsichord', 'dulcimer', 'zither', 'lute', 'lyre', 'concertina', 'melodica', 'kazoo', 'recorder', 'piccolo'],
  moreclothing: ['waistcoat', 'petticoat', 'pinafore', 'kimono', 'sarong', 'tunic', 'vestment', 'mantle', 'cloak', 'cape', 'hood', 'shawl'],
  moremammals: ['pangolin', 'aardvark', 'wolverine', 'badger', 'marten', 'polecat', 'stoat', 'muskrat', 'vole', 'shrew', 'mole', 'bat'],
  moregems: ['tourmaline', 'moonstone', 'labradorite', 'malachite', 'lapis', 'jasper', 'agate', 'chalcedony', 'beryl', 'spinel'],
  moremythical: ['leprechaun', 'banshee', 'gargoyle', 'wraith', 'specter', 'phantom', 'poltergeist', 'genie', 'djinn', 'oracle'],
  moreseasons: ['thaw', 'bloom', 'wilt', 'harvest', 'frost', 'bud', 'sprout', 'wither', 'ripen', 'blossom'],
  desserts3: ['baklava', 'churro', 'beignet', 'cannoli', 'strudel', 'linzer', 'palmier', 'madeleine', 'financier', 'petitfour'],
  moreveg2: ['scallion', 'pumpkin', 'butternut', 'acorn', 'delicata', 'chayote', 'plantain', 'yucca', 'taro', 'cassava'],
  travelwords: ['passport', 'itinerary', 'souvenir', 'postcard', 'luggage', 'suitcase', 'backpack', 'compass', 'roadmap', 'wanderlust'],
  cottagecore: ['gingham', 'quilt', 'wildflower', 'meadow', 'apron', 'basket', 'lantern', 'clothesline', 'porch', 'hammock', 'birdsong', 'breeze'],
  farmmarket: ['farmstand', 'basket', 'burlap', 'crate', 'harvest', 'orchard', 'honeycomb', 'preserves', 'pickles', 'cider'],
  weatherwords2: ['sunshower', 'heatwave', 'coldsnap', 'windchill', 'thundercloud', 'raincloud', 'snowsquall', 'icestorm', 'dust', 'fog'],
  papergoods: ['origami', 'confetti', 'streamer', 'garland', 'pinwheel', 'kite', 'lantern', 'envelope', 'wrapping', 'ribbon'],

  moreprofessions: ['locksmith', 'goldsmith', 'silversmith', 'cartwright', 'stonemason', 'chimneysweep', 'lamplighter', 'watchmaker', 'clockmaker', 'bookbinder', 'winemaker', 'cheesemaker'],
  morecelestial: ['supernova', 'planetarium', 'observatory', 'lightyear', 'blackhole', 'starburst', 'moonlight', 'sunspot', 'solstice', 'equinox'],
  morefantasy: ['spellcaster', 'shapeshifter', 'stormcloud', 'thunderbolt', 'firestorm', 'icestorm', 'windwalker', 'earthquake', 'avalanche', 'whirlpool'],
  morefood: ['casserole', 'potpie', 'stirfry', 'dumpling', 'meatball', 'porridge', 'oatcake', 'flatbread', 'cornbread', 'gingerbread', 'shortcake', 'cheesecake'],
  moretoys: ['jackknife', 'slingshot', 'boomerang', 'periscope', 'kaleidoscope', 'spyglass', 'compass', 'binoculars', 'magnifier', 'pinwheel'],
  moreweather: ['sunshine', 'moonshine', 'starshine', 'rainstorm', 'snowstorm', 'thunderstorm', 'hailstorm', 'sandstorm', 'duststorm', 'windstorm'],
  morehousehold: ['bookend', 'candlestick', 'inkwell', 'paperweight', 'letteropener', 'hourglass', 'weathervane', 'birdcage', 'lampstand', 'umbrella'],
  moreanimalhomes: ['anthill', 'beehive', 'birdnest', 'squirreldrey', 'foxden', 'rabbithole', 'wolfden', 'bearcave', 'spiderweb', 'wasp'],
  morecraft: ['macrame', 'découpage', 'pyrography', 'marquetry', 'filigree', 'engraving', 'etching', 'embossing', 'gilding', 'lacquering'],
  moreadventure: ['shipwreck', 'castaway', 'stowaway', 'buccaneer', 'privateer', 'swashbuckler', 'adventurer', 'trailblazer', 'frontiersman', 'homesteader'],

  finalnature: ['wildflower', 'underbrush', 'evergreen', 'deadwood', 'driftwood', 'petrified', 'sagebrush', 'goldenrod', 'milkweed', 'ragweed', 'crabgrass', 'clover'],
  finalfood: ['jambalaya', 'succotash', 'coleslaw', 'guacamole', 'quesadilla', 'empanada', 'croquette', 'fritter', 'tempura', 'antipasto'],
  finalhome: ['footstool', 'rockingchair', 'bookcase', 'writingdesk', 'umbrella', 'doorbell', 'welcomemat', 'housecoat', 'nightstand', 'headboard'],
  finalwhimsy: ['snowglobe', 'musicbox', 'jackinbox', 'rubberduck', 'paperboat', 'sandcastle', 'bubblegum', 'cottoncandy', 'popcorn', 'lemonade'],
  finalcreatures: ['hedgehog', 'porcupine', 'chinchilla', 'lemming', 'gopher', 'prairiedog', 'woodchuck', 'groundhog', 'possum', 'bandicoot'],

  lastwave1: ['buttermilk', 'gingersnap', 'applesauce', 'butterscotch', 'peppermint', 'spearmint', 'wintergreen', 'huckleberry', 'boysenberry', 'elderflower'],
  lastwave2: ['woodshed', 'toolshed', 'cowshed', 'henhouse', 'doghouse', 'birdhouse', 'boathouse', 'icehouse', 'smokehouse', 'roundhouse'],
  lastwave3: ['nightowl', 'earlybird', 'daydreamer', 'moonchild', 'starchild', 'sunflower', 'moonflower', 'nightshade', 'morningstar', 'eveningstar'],
  lastwave4: ['papercraft', 'woodcraft', 'stonecraft', 'metalcraft', 'glasswork', 'ironwork', 'brickwork', 'stonework', 'latticework', 'lacework'],

  lastwave5: ['candlewick', 'lampwick', 'firelight', 'moonglow', 'sunglow', 'afterglow', 'twilight', 'daylight', 'skylight', 'starlight'],
  lastwave6: ['appletree', 'peartree', 'plumtree', 'cherrytree', 'olivetree', 'lemontree', 'orangetree', 'pinetree', 'firtree', 'yewtree'],
  lastwave7: ['woodsmoke', 'campsmoke', 'chimneysmoke', 'incense', 'potpourri', 'sachet', 'perfume', 'fragrance', 'aroma', 'scent'],
  lastwave8: ['handbasket', 'gift', 'ribbon', 'wrapping', 'greeting', 'postcard', 'letter', 'parcel', 'package', 'delivery'],

  lastwave9: ['cupboard', 'sideboard', 'headboard', 'cardboard', 'clipboard', 'chalkboard', 'surfboard', 'skateboard', 'washboard', 'keyboard'],
  lastwave10: ['barnstorm', 'brainstorm', 'snowstorm', 'sandstorm', 'thunderstorm', 'rainstorm', 'firestorm', 'windstorm', 'hailstorm', 'duststorm'],

  lastwave11: ['pinecone', 'pineapple', 'pinewood', 'pineforest', 'oakwood', 'oakleaf', 'oaktree', 'mapleleaf', 'maplesyrup', 'maplewood'],
  lastwave12: ['honeybee', 'honeycomb', 'honeydew', 'honeysuckle', 'honeypot', 'honeymoon', 'moonpie', 'moonflower', 'moonbeam', 'moonrock'],

  lastwave13: ['seashore', 'seaside', 'seafarer', 'seafaring', 'seaport', 'seafront', 'seascape', 'landscape', 'moonscape', 'streetscape'],
  lastwave14: ['woodpile', 'woodshed', 'woodstove', 'woodsmoke', 'woodgrain', 'woodchip', 'woodlark', 'woodmouse', 'woodruff', 'woodrush'],
  lastwave15: ['barnowl', 'snowowl', 'screechowl', 'hornedowl', 'barnswallow', 'treeswallow', 'cliffswallow', 'housesparrow', 'housefinch', 'housewren'],

  lastwave16: ['riverbank', 'riverbed', 'riverside', 'riverboat', 'lakeside', 'lakefront', 'lakeshore', 'seabed', 'seafloor', 'seacoast'],

  lastwave17: ['hilltop', 'hillside', 'hillock', 'foothills', 'treetop', 'rooftop', 'mountaintop', 'cliffedge', 'cliffface', 'clifftop'],
};
